version: '3.9'

services:
  app:
    build: .
    container_name: trading_ai_system
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: always
